### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by King-BR** [Jinzulen/DEmojiJS#4]
when i try to start my discord bot after i updated the NPM to version 1.3.2 this error occur
![image](https://user-images.githubusercontent.com/51011050/79622161-8463ed80-80ec-11ea-83bb-013f6a68fb8b.png)

**Comment by King-BR** [comment]
just tested with version 1.2.0 and the error don't occurs

**Comment by Jinzulen** [comment]
@King-BR Hello, could you please provide me with more information? What data are you trying to access and through which functions?

I can't seem to reproduce this error and this is the first time it's been reported to me, any insight you could provide into how it occurred would be appreciated.

**Comment by King-BR** [comment]
@Jinzulen hello, the only function im using right now is .allEmoji()
But the error occurs right when i try to start the bot with nodemon, it doesnt even give me the chance to use the command
I dont know if its giving the error because of some incompatibility with some other NPM or with Discord.js (V12.2.0)

**Comment by Jinzulen** [comment]
@King-BR Hello, I just pushed a fix with v1.3.4 that tended to an issue that prevented the cache from being cleared on startup. This _might_ have contributed to the error, I'm not sure, but could you please also make sure that the program has write permissions? DEmojiJS needs to create a cache directory and JSON storage.

Please update to v1.3.4 and check permissions and report back to me if the issue persists.

**Comment by King-BR** [comment]
Im not at home right now so i cant test. But i will test it and report as soon as i can

**Comment by Jinzulen** [comment]
@King-BR Can you also please try to add `"ignore": "DiscordEmoji.json"` to your Nodemon config file?

That resolved all the problems I was having with Nodemon, and I'm curious to see if it caused the problem you were having.

**Comment by Jinzulen** [comment]
@King-BR Can you also please try to add `"ignore": "DiscordEmoji.json"` to your Nodemon config file?

That resolved all the problems I was having with Nodemon, and I'm curious to see if it caused the problem you were having.

**Comment by King-BR** [comment]
Ok, i will try that

**Comment by King-BR** [comment]
@Jinzulen im still getting the same error
I already put the "ignore": "DiscordEmoji.json" on nodemon config and i still get the error

**Comment by Jinzulen** [comment]
@King-BR `demoji-cache`? That's the name of cache file in v1.2.0, there is no reason why the current version would create that. Can you please try manually deleting the current DEmojiJS installation from your node_modules directory and specifically install the current version by way of `npm i demojijs@1.3.4`?

**Comment by King-BR** [comment]
@Jinzulen its working now thks

**Comment by Jinzulen** [comment]
@King-BR Are you sure? No errors, no warnings, nothing?

**Comment by King-BR** [comment]
@Jinzulen the only warning showing is about conditional exports
![image](https://user-images.githubusercontent.com/51011050/79645277-bf196480-8184-11ea-8917-a7cb487ad973.png)

**Comment by Jinzulen** [comment]
@King-BR You can safely ignore that warning, I've seen it thrown countless times in bot development and apart from occupying space in your terminal output, it's not actually indicative of any errors or problems or the like.

In any case, I'm glad this was resolved, happy coding! And please, don't hesitate to open a new issue should you encounter any problem at all with DEmojiJS!

**Comment by King-BR** [comment]
@Jinzulen thks for the help
