### ISSUE TITLE
I got an error.

### ISSUE THREAD

**Issue by TheClashFruit** [Jinzulen/DEmojiJS#7]
```
 /app/node_modules/demojijs/lib/API/EmojiAPI.js:18
           throw Error;
           ^
 # [DEmojiJS] Could not issue request @ https://discordemoji.com/api/?request=categories
 (Use `node --trace-uncaught ...` to show where the exception was thrown)
```

**Comment by Jinzulen** [comment]
That's just the generic response to being met with a HTTP response status code that isn't 200, indicating an unsuccessful request to the server, after testing both DEmojiJS and other similar tools and getting back the 503 status code, I can confidently say that this isn't a bug or an error on the part of DEmojiJS, but rather on that of Discord Emoji themselves.

My advice would be to wait it out until they sort out whatever it is that's happening on their end that's causing this.

**Comment by Jinzulen** [comment]
@TheClashFruit That's just the generic response to being met with a HTTP response status code that isn't 200, indicating an unsuccessful request to the server, after testing both DEmojiJS and other similar tools and getting back the 503 status code, I can confidently say that this isn't a bug or an error on the part of DEmojiJS, but rather on that of Discord Emoji themselves.

My advice would be to wait it out until they sort out whatever it is that's happening on their end that's causing this.
